package CalculatorModule;


/**
* CalculatorModule/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculatorModule.idl
* Friday, 26 May, 2023 2:48:07 PM IST
*/

public interface CalculatorOperations 
{
  int add (int a, int b);
} // interface CalculatorOperations
