package ConcatModule;


/**
* ConcatModule/Concat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConcatModule.idl
* Friday, 26 May, 2023 3:54:48 PM IST
*/

public interface Concat extends ConcatOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Concat
